### ISSUE TITLE
Replace headline banner on CC home page

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/website#1]
on: http://creativecommons.org - Biz Models is still locked in as highlighted topic. It's been there a long time ... and the Kickstarter campaign is over.

Can we change the main highlighted topic to (a) CC Summit or (b) other new (rotating) announcements?

Thanks.

**Comment by mattl** [comment]
What do you want to put here now?

**Comment by cablegreen** [comment]
How about the Summit? https://summit.creativecommons.org

**Comment by mattl** [comment]
WDYT @rebeccalendl? we already have stuff about the summit. I don't know if we want/need more.

**Comment by rebeccakross** [comment]
How about we do big banner in the main spot with CC GS logo, focusing on
sharing out the event and inviting attendance. Then below left is the CC
Global Summit small content panel, focusing on the announcement of the
programs/sessions (is there a nice image for that?). Then below right is
the PIA plug. Below all of that (ie. 3rd row) is the 'how can I license'
and 'latest news' stuff.

We could coordinate this update with Thursday's big GS outreach and program
announcement push?

Rebecca Lendl
Director of Development
Creative Commons
rebecca@creativecommons.org

**Comment by mattl** [comment]
Let's keep the other stuff where it is, but maybe update the bottom left
image with another CTA for the schedule?

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by rebeccakross** [comment]
works for me.

has their already been a suggestion to incorporate the GS logo at
https://summit.creativecommons.org/? would offer a nice visual link from
our new homepage banner with GS logo to the GS site itself

Rebecca Lendl
Director of Development
Creative Commons
rebecca@creativecommons.org

**Comment by mattl** [comment]
Yeah, we'll be adding that ASAP.

---

Matt Lee
Creative Commons
Boston, MA, USA
